I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 600, in script
Exception: Sayer 'soderC' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 600, in script
  File "C:\Users\SANE\Desktop\ETC\renpy-7.1.1-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\SANE\Desktop\ETC\renpy-7.1.1-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'soderC' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Project 1.0
Sat Mar 16 11:28:27 2019
