I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 257, in script
    d "ก็มาดิคร้าบบ!"
Exception: Sayer 'd' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 257, in script
    d "ก็มาดิคร้าบบ!"
  File "C:\Users\SANE\Downloads\renpy-7.2.0-sdk\renpy\ast.py", line 660, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\SANE\Downloads\renpy-7.2.0-sdk\renpy\ast.py", line 564, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'd' is not defined.

Windows-8-6.2.9200
Ren'Py 7.2.0.424
Project 1.0
Fri Mar 15 15:15:11 2019
